- name: Create mountable dir
  file: path=/opt/nfs state=directory mode=777 owner=root group=root
- name: Ensure NFS utilities are installed.
  yum:
    name:
      - nfs-utils
    state: present
- name: copy /etc/exports
  template: src=exports.j2 dest=/etc/exports owner=root group=root

- name: restart nfs server
  service: name=nfs-server state=restarted
