domain   = 'local'

# use two digits id below, please
nodes = [
  { :hostname => 'test1', :id => '01' },
  { :hostname => 'test2', :id => '02' },
]

memory = 1024

$script = <<SCRIPT
cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
rm -f /home/vagrant/.ssh/id_rsa.pub
SCRIPT

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "bento/ubuntu-16.04"
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network "public_network"
      nodeconfig.vm.provider :vmware_fusion do |vb|
        vb.gui = false
        vb.vmx["ethernet0.pcislotnumber"] = "32"
        vb.name = node[:hostname]+"."+domain
        vb.memory = memory
        vb.cpus = 1
        vb.vmx["ethernet1.generatedAddress"] = nil
        vb.vmx["ethernet1.addressType"] = "static"
        vb.vmx["ethernet1.address"] = "5c:a1:ab:1e:00:"+node[:id]
      end
      nodeconfig.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
      nodeconfig.vm.provision "shell", inline: $script
    end
  end
  config.vm.provider "vmware_fusion"
end
